version: '3'
services:
  app:
    command: ["alembic","upgrade","head"]
    environment:
      DB_HOST: postgresql://root:root@capas_db/root
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - capas_db
    networks:
      - mynet
  capas_db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
      - mynet
volumes:
  db-data:
networks:
  mynet:
    driver: bridge