version: '3'
services:
  app:
    command: bash
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - mydb
  mydb:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  db-data: